# Generated by Django 4.1.3 on 2022-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(default='user', max_length=500),
            preserve_default=False,
        ),
    ]
