# Generated by Django 4.1.3 on 2022-12-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('bodyTarget', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('MET', models.IntegerField()),
                ('video', models.CharField(max_length=500)),
                ('equipments', models.ManyToManyField(to='workout_plan.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default='160', max_length=100)),
                ('weight', models.FloatField(default='60', max_length=100)),
                ('goal', models.CharField(default='Lose Weight', max_length=100)),
                ('fitnessLevel', models.CharField(default='inactive', max_length=100)),
                ('trainingLevel', models.CharField(default='Inactive', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('disablities', models.ManyToManyField(default='None', to='workout_plan.disability')),
                ('equipments', models.ManyToManyField(default='None', to='workout_plan.equipment')),
                ('exercies', models.ManyToManyField(to='workout_plan.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('workoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_plan.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='Day_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('numberOfSets', models.IntegerField()),
                ('numberOfReps', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_plan.exercise')),
                ('workoutPlanDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_plan.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='exercises',
            field=models.ManyToManyField(through='workout_plan.Day_Exercise', to='workout_plan.exercise'),
        ),
        migrations.AddField(
            model_name='day',
            name='workoutPlanWeek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_plan.week'),
        ),
    ]
